dist: xenial
language: node_js
node_js:
  - 13.1
services:
  - xvfb
addons:
  firefox: "34.0"
sudo: false
before_script:
  - gem install sass
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - grunt dev
